//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourCommunityWorkshopWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int ToolId { get; set; }
        public string ToolName { get; set; }
        public string BrandName { get; set; }
        public bool Active { get; set; }
        public bool Availability { get; set; }
        public string ToolCondition { get; set; }
    }
}
